# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-24 15:34
from __future__ import unicode_literals

from django.db import migrations
import gm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_quickblocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickblock',
            name='items',
            field=gm2m.fields.GM2MField(help_text=b'The items this story is all about', related_name='stories', through_fields=(b'gm2m_src', b'gm2m_tgt', b'gm2m_ct', b'gm2m_pk')),
        ),
    ]
